version: "2"
services:
    web:
        image: nginx:latest
        volumes:
            - ./webroot:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_PORT=80
        networks:
            - private
        depends_on:
            - app1
            - app2

    app1:
        image: php:7.1-fpm
        volumes:
            - ./webroot:/var/www/html
        networks:
            - private

    app2:
        image: php:7.1-fpm
        volumes:
            - ./webroot:/var/www/html
        networks:
            - private

networks:
    private:
        driver: bridge
